@echo off
setlocal
cd /d "%~dp0ServerEmulator"

if not exist node_modules (
  echo [ServerEmulator] Installing dependencies...
  npm install
)

if "%LOG_ALL%"=="" set LOG_ALL=1

if "%~1"=="" (
  set PORT=61000
) else (
  set PORT=%~1
)

if "%~2"=="" (
  set MODE=normal
) else (
  set MODE=%~2
)

if /I "%MODE%"=="login" (
  set FAST_LOGIN=1
  set PACKET_LOG=full
  set PACKET_LOG_IDS=0x6D
  set PACKET_LOG_INTERVAL_MS=0
  set PACKET_LOG_REPEAT_SUPPRESS_MS=0
  set PACKET_LOG_ANALYSIS=1
  set PACKET_HANDLER_VERBOSE=0
) else if /I "%MODE%"=="lithdebug" (
  set PACKET_LOG=summary
  set PACKET_LOG_IDS=0x40
  set PACKET_LOG_INTERVAL_MS=5000
  set PACKET_LOG_REPEAT_SUPPRESS_MS=2000
  set PACKET_LOG_ANALYSIS=1
  set PACKET_HANDLER_VERBOSE=0
  set LITH_DEBUG_BURST=10
  set LITH_DEBUG_TRIGGER=first_lith
  set LITH_DEBUG_HEX_BYTES=64
  set LITH_DEBUG_RAW=1
  set LITH_DEBUG_RAW_BYTES=512
  set LITH_DEBUG_RAW_MIN=160
  set LITH_DEBUG_RAW_MAX=256
  set LITH_DEBUG_SCAN=1
  set LITH_DEBUG_SCAN_ANY=1
  set LITH_DEBUG_SCAN_MAX=20
  set LITH_DEBUG_SCAN_PAYLOAD_BYTES=32
  set LITH_HAS_MORE_FLAG=0
  set LITH_DEBUG_BITS=1
  set LITH_DEBUG_BITS_PER_LINE=128
  set LITH_DEBUG_BITS_MAX=0
  set LITH_DEBUG_LOG=1
  set LITH_DEBUG_LOG_PATH=logs\lithdebug.log
  set FORCE_LOGIN_ON_FIRST_LITH=0
) else if /I "%MODE%"=="forcelogin" (
  set PACKET_LOG=summary
  set PACKET_LOG_IDS=0x40
  set PACKET_LOG_INTERVAL_MS=5000
  set PACKET_LOG_REPEAT_SUPPRESS_MS=2000
  set PACKET_LOG_ANALYSIS=1
  set PACKET_HANDLER_VERBOSE=0
  set LITH_DEBUG_BURST=0
  set LITH_DEBUG_TRIGGER=none
  set LITH_DEBUG_HEX_BYTES=64
  set LITH_DEBUG_LOG=0
  set FORCE_LOGIN_ON_FIRST_LITH=1
) else (
  set PACKET_LOG=summary
  set PACKET_LOG_IDS=0x40
  set PACKET_LOG_INTERVAL_MS=5000
  set PACKET_LOG_REPEAT_SUPPRESS_MS=2000
  set PACKET_LOG_ANALYSIS=1
  set PACKET_HANDLER_VERBOSE=0
  set LITH_DEBUG_BURST=0
  set LITH_DEBUG_TRIGGER=none
  set LITH_DEBUG_HEX_BYTES=64
  set LITH_DEBUG_LOG=0
  set FORCE_LOGIN_ON_FIRST_LITH=0
)

if /I "%LOG_ALL%"=="1" (
  set PACKET_LOG=full
  set PACKET_LOG_IDS=
  set PACKET_LOG_INTERVAL_MS=0
  set PACKET_LOG_REPEAT_SUPPRESS_MS=0
  set PACKET_LOG_ANALYSIS=1
  set PACKET_HANDLER_VERBOSE=1
  set LOGIN_DEBUG=1
  set LITH_DEBUG_RAW=1
  set LITH_DEBUG_RAW_BYTES=1400
  set LITH_DEBUG_RAW_MIN=1
  set LITH_DEBUG_RAW_MAX=1400
  set LITH_DEBUG_SCAN=1
  set LITH_DEBUG_SCAN_ANY=1
  set LITH_DEBUG_SCAN_MAX=0
  set LITH_DEBUG_BITS=1
  set LITH_DEBUG_BITS_PER_LINE=128
  set LITH_DEBUG_BITS_MAX=0
  set LITH_DEBUG_LOG=1
  set LITH_DEBUG_LOG_PATH=logs\lithdebug.log
)

set PACKET_HANDLER_LOG_THROTTLE_MS=0
set WORLD_IP=127.0.0.1
set WORLD_PORT=61000

echo [ServerEmulator] Starting server on UDP port %PORT%...
echo [ServerEmulator] Mode=%MODE%
echo [ServerEmulator] Packet log: %PACKET_LOG% interval=%PACKET_LOG_INTERVAL_MS% ids=%PACKET_LOG_IDS%
echo [ServerEmulator] FAST_LOGIN=%FAST_LOGIN% WORLD=%WORLD_IP%:%WORLD_PORT%
npm run dev
