/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'CShell.dll'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct HINSTANCE__;

/* 1 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 2 */
typedef struct _GUID GUID;

/* 3 */
typedef struct HINSTANCE__ *HINSTANCE;

/* 4 */
struct HINSTANCE__
{
  int unused;
};

/* 5 */
typedef unsigned int DWORD;

/* 6 */
typedef void *LPVOID;

/* 7 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 8 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 10 */
typedef unsigned __int16 WORD;

/* 9 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 11 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 12 */
typedef char CHAR;

/* 13 */
struct std::exception;

/* 14 */
#pragma pack(push, 2)
struct Packet_ID_WORLD_LOGIN
{
  void *vftable;
  unsigned __int8 _pad0[1060];
  unsigned __int8 id;
  unsigned __int8 _pad1[7];
  unsigned __int8 worldId;
  unsigned __int8 worldInst;
  unsigned __int8 _pad2[2];
  unsigned int playerId;
  unsigned int worldConst;
};
#pragma pack(pop)

/* 15 */
#pragma pack(push, 2)
struct SystemAddress6
{
  unsigned int ip;
  unsigned __int16 port;
};
#pragma pack(pop)

/* 20 */
#pragma pack(push, 2)
struct SystemAddress6u
{
  unsigned int ip;
  unsigned int port_pad;
};
#pragma pack(pop)

/* 16 */
#pragma pack(push, 2)
struct Packet_ID_WORLD_LOGIN_RETURN
{
  void *vftable;
  unsigned __int8 _pad0[1060];
  unsigned __int8 id;
  unsigned __int8 _pad1[7];
  unsigned __int8 code;
  unsigned __int8 flag;
  unsigned __int8 _pad2[2];
  SystemAddress6u worldAddr;
};
#pragma pack(pop)

/* 17 */
#pragma pack(push, 2)
struct Packet_Id107
{
  char _pad0[1072];
  unsigned __int16 subId;
  unsigned int optA;
  unsigned int optB;
  unsigned int optC;
  unsigned int optD;
  char strA[128];
  char strB[128];
};
#pragma pack(pop)

/* 18 */
#pragma pack(push, 2)
struct SystemAddress6u::$9B9B964092903CEAD27F1C93F21C15EE::$A07826A6785D4640C2ECF688C5FB3F8E
{
  unsigned __int16 port;
  unsigned __int16 pad;
};
#pragma pack(pop)

/* 19 */
#pragma pack(push, 2)
union SystemAddress6u::$9B9B964092903CEAD27F1C93F21C15EE
{
  unsigned int port_pad;
  #pragma pack(push, 2)
  struct
  {
    unsigned __int16 port;
    unsigned __int16 pad;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 21 */
#pragma pack(push, 2)
struct WorldLoginReturnAddrPacked
{
  unsigned int flag_pad_ip0;
};
#pragma pack(pop)

/* 22 */
struct Packet_7B_List
{
  _BYTE unk0;
  _BYTE gap1[3];
  _BYTE begin;
  _BYTE gap5[3];
  _BYTE end;
  _BYTE gap9[3];
  _BYTE capacity;
};

/* 23 */
struct Packet_7B_ItemsAddedPayload
{
  _BYTE itemCount;
  __declspec(align(2)) _BYTE pad_02;
  __declspec(align(2)) Packet_7B_List entries;
  _BYTE gap11[3];
  _BYTE optA;
  _BYTE gap15[3];
  _BYTE optB;
  _BYTE gap19[3];
  _BYTE optC;
  _BYTE gap1D[3];
  _BYTE flags;
  _BYTE pad_21;
};

/* 24 */
struct __unaligned __declspec(align(1)) Packet_ID_7B
{
  _BYTE gap0[1072];
  int playerId;
  char subId;
  char worldId;
  char worldInst;
  char unk_437;
  Packet_7B_ItemsAddedPayload itemsAdded;
  _BYTE gap45A[2];
  int subId3_value;
  Packet_7B_List subId6_list;
};

/* 25 */
struct RBTreeHeader
{
  int unk0;
  int root;
  int size;
};

/* 26 */
#pragma pack(push, 2)
struct ItemStructA
{
  unsigned __int16 templateId;
  unsigned __int16 stackCount;
  unsigned __int16 ammoOverrideId;
  unsigned __int16 durabilityCur;
  unsigned __int8 durabilityLossPct;
  unsigned __int8 bindState;
  unsigned __int8 pad_0A;
  unsigned __int8 pad_0B;
  unsigned int identityKeyA;
  unsigned int u32_tooltipValue;
  unsigned int identityKeyB;
  unsigned __int8 qualityBonusPct;
  unsigned __int8 qualityTier;
  unsigned __int8 variantIndex;
  unsigned __int8 variantRoll[4];
  unsigned __int8 pad_1F;
};
#pragma pack(pop)

/* 30 */
#pragma pack(push, 2)
struct VariantIdSetHeader
{
  unsigned int comp;
  void *head;
  unsigned int nodeCount;
};
#pragma pack(pop)

/* 27 */
#pragma pack(push, 2)
struct ItemsAddedEntry
{
  ItemStructA item;
  VariantIdSetHeader variantIdSet;
};
#pragma pack(pop)

/* 28 */
#pragma pack(push, 2)
struct ItemEntryWithId
{
  unsigned int entryId;
  ItemStructA item;
};
#pragma pack(pop)

/* 29 */
struct __packed;

/* 31 */
#pragma pack(push, 2)
struct ItemsAddedEntryVec
{
  unsigned int unk0;
  ItemsAddedEntry *begin;
  ItemsAddedEntry *end;
  ItemsAddedEntry *capacity;
};
#pragma pack(pop)

/* 32 */
#pragma pack(push, 2)
struct ItemsAddedPayload
{
  unsigned __int16 baseUsedCount;
  unsigned __int16 pad_02;
  ItemsAddedEntryVec entries;
  unsigned int capacity;
  unsigned int unk24;
  unsigned int unk28;
};
#pragma pack(pop)

/* 33 */
#pragma pack(push, 2)
struct Packet_ID_7B_SubId6Payload
{
  unsigned __int8 _unk0[16];
  unsigned int meta_a;
  unsigned int meta_b;
  unsigned int meta_c;
};
#pragma pack(pop)

/* 34 */
#pragma pack(push, 2)
struct MsgId6B_HandlerEntry
{
  void *vftable;
  unsigned int unk04;
  unsigned int unk08;
  unsigned int unk0C;
  unsigned int id;
};
#pragma pack(pop)

/* 35 */
#pragma pack(push, 2)
struct MsgId6B_GroupBucket
{
  MsgId6B_HandlerEntry **entries;
  unsigned int unk04;
  unsigned int count;
  unsigned int unk0C;
};
#pragma pack(pop)

/* 36 */
#pragma pack(push, 2)
struct CrosshairMgr
{
  char _pad0[424];
  float spreadCooldownMs;
  float spreadLastTime;
  int targetMode;
  int lastTargetMode;
  unsigned __int8 targetModeIsSpecial;
};
#pragma pack(pop)

/* 37 */
#pragma pack(push, 2)
struct CGameClientShell
{
  char _pad0[36];
  float recoilScale;
};
#pragma pack(pop)

/* 38 */
#pragma pack(push, 2)
struct Packet_ID_LOGIN_RETURN
{
  unsigned __int8 base[1072];
  unsigned __int8 status;
  unsigned __int8 pad_0x431[3];
  unsigned int playerID;
  unsigned __int8 accountType;
  unsigned __int8 field4_0x439;
  unsigned __int8 field5_0x43A;
  unsigned __int8 pad_0x43B;
  unsigned __int16 clientVersion;
  unsigned __int8 isBanned;
  unsigned __int8 banLength[16];
  unsigned __int8 banReason[129];
};
#pragma pack(pop)

/* 39 */
#pragma pack(push, 2)
struct Packet_ID_LOGIN_TOKEN_CHECK
{
  unsigned __int8 base[1072];
  unsigned __int8 fromServer;
  unsigned __int8 success;
  unsigned __int8 requestToken[32];
  unsigned __int8 username[32];
};
#pragma pack(pop)

/* 40 */
typedef unsigned int size_t;

/* 41 */
typedef char *va_list;

/* 42 */
struct std::ios_base;

